### ISSUE TITLE
Build the side Nav component for logged in Users

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#10]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. sideNavOne.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the sideNav-one folder, also within the app, so that I can access it when navigating to the / sideNav-one route.

**Comment by Ibinola** [comment]
Can I take care of this issue?

**Comment by kcmikee** [comment]
I am kcmikee, a frontend developer with 4+ years of experience working with React, Next.js, and TypeScript. 

 My approach to this task will include:
1. Reviewing the project structure, Figma designs, and any relevant files.
2. Implementing the sidebar, ensuring it adheres to the application's color scheme and branding.
3. Make sure it doesn't affect the application performance


 Estimated Time (ET): 12 hrs.

**Comment by BigBen-7** [comment]
Hi, I’m Bernard, a Frontend Developer. After reviewing the issues and guidelines, I’m confident I can commit to resolving them within the described ETA. Would it be okay for me to tackle this issue?

**Comment by Ugo-X** [comment]
@kcmikee assigned, please join the telegram group: https://t.me/explorebeyondzerocheck
