### ISSUE TITLE
Build the login page

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#11]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. login.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the login folder, also within the app, so that I can access it when navigating to the / login route.

**Comment by sublime247** [comment]
I would like to work on this Asap

**Comment by sublime247** [comment]
Cloned and trying to run but getting an error stating app_id not set in the environment variable

'''  11 |   if (!app_id) {
> 12 |     throw new Error('app_id is not set in environment variables!');
     |           ^
  13 |   }
  14 |   if (!action) {
  15 |     throw new Error('action is not set in environment variables!'); '''

**Comment by sublime247** [comment]
gotten!
