### ISSUE TITLE
Build the Event Details Modal component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#2]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. eventModal.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the eventDetails-modal folder, also within the app, so that I can access it when navigating to the /eventDetails-modal route.

#### Please endeavour to deliver task in above ETA. Failure to do so results in issue being reassigned

**Comment by Benjtalkshow** [comment]
Would love to work on this @Ugo-X

**Comment by 3th-Enjay** [comment]
Hello after going through the figma file , I have a clear understanding of what needs to be done and how to go about it with my experience in Frontend

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through the Design, Study, and be in sync with the flow of the Design
- I will then start the Event Details Modal component UI implementation inside the `app/eventDetails-modal/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, e.t.c
- I will make sure the UI implementation works across all devices

## ETA
12 hours as stated above

**Comment by emarc99** [comment]
Is this issue still available?

**Comment by BigBen-7** [comment]
Can I handle this task?

**Comment by sublime247** [comment]
I would like to take up this task @Ugo-X

**Comment by Holamite** [comment]
## About me
I’m passionate about making Web3 technology more accessible. We all know that user experience is one of the biggest challenges and barriers to bringing new users into the decentralized world. That’s why I focus on creating intuitive and user-friendly applications powered by smart contracts.

## My Plan
If assigned this task, I will review the Figma design to ensure the eventModal.tsx component matches the provided specifications. I’ll create the file in the components folder, implement the design and functionality, and then import it into the page.tsx file in the eventDetails-modal folder. This will ensure it works seamlessly with the /eventDetails-modal route. I’ll test the component for responsiveness and functionality and deliver it within the 12-hour ETA. If I face any issues or have suggestions, I’ll communicate promptly to ensure smooth progress.

**Comment by Levi-Ojukwu** [comment]
Hello @Ugo-X, Can I take care of this issue?

## About Me 
I am a web3 full stack developer and an alumni of Web3Bridge, with blockchain technology and frontend engineering expertise. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How To Resolve Issue
- To tackle this issue, I will first of all study the UI design properly to understand the number variables and the page flow, for a better page dimensions and layouts.
- Then inside the component folder, I will create a file named `EventDetailsModal.tsx`
- I will then import the `EventDetailsModal.tsx` component into  the `app/eventDetails-modal/page.tsx` file and beging the page implementation.
- I will ensure a responsive page implementation, making sure it works across all devices.

If assigned this issue, I will ensure compliance with the project's guidelines.

## ETA
8 - 10 Hours max

**Comment by phertyameen** [comment]
I am a new contributor and can handle this modal creation.

**Comment by portableDD** [comment]
Hi, I am Emmanuel Dorcas, a software developer with React js and Typescript.
my estimated timeframe is 10 hours:

how I will tackle this:
1. first create a file called eventModal.tsx
2. then i import it inside the page.ts inside the eventDetails-modal folder
3. then using tailwind css, i will use an array to create the modal
thanks.

**Comment by Ugo-X** [comment]
Assigned please join the telegram group
