### ISSUE TITLE
Build Explore Categories Component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#20]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. explore-category.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the explore-category folder, also within the app, so that I can access it when navigating to the / explore-category .

**Comment by 3th-Enjay** [comment]
Could I be assigned to this? i am skilled and quick enough to deliver within the expected eta

**Comment by portableDD** [comment]
Is it okay if I take this?

My name is Dorcas, a software developer with React and Typescript, my eta is 4 hours, and I will tackle this issue, by using an array for the components and then map through it, and tailwind css for the styling 

Thanks

**Comment by KuchiMercy** [comment]
Can I take care of this issue?

**Comment by Levi-Ojukwu** [comment]
Hello, @Ugo-X, I would like to work on this issue.

##About Me
I am a Web3 full-stack developer and alumni of Web3Bridge, with expertise in blockchain technology and frontend engineering. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries.

## How To Tackle This Issue
-  To tackle this issue, I will first study the UI design properly to understand the design's number variables and the page flow, for better page dimensions and layouts.
- I will create a component file named `ExploreCategory`.
- I will then import the `EventLoggedInUser` components inside the `app/explore-category/page.tsx` file.
- I will ensure a responsive page implementation, making sure it works across all devices.

If assigned this issue, I will ensure compliance with the project's guidelines.

## ETA
5 Hours

**Comment by Emmanex01** [comment]
Can I handle this task?

**Comment by Ugo-X** [comment]
assigned, please join the telegram group:  https://t.me/explorebeyondzerocheck

**Comment by Ugo-X** [comment]
@3th-Enjay reassigned to you, 6 hours ETA.

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, specializing in frontend technologies such as React, NextJS, and Javascript/Typescript. I am a recent graduate of Web3bridge Africa, the foremost blockchain developer community, and have contributed to several open-source projects. I'm excited to bring my expertise to this project.

For building the Explore Categories component, my approach will be:

Review the Project Requirements and Design: I will begin by reviewing the project structure, Figma designs (if available), and any other relevant resources to ensure a clear understanding of the design and functionality requirements for the Explore Categories component.

Develop the Explore Categories Component: I will build a dynamic, reusable, and scalable component to display different categories of content or events. This will include the design and implementation of category cards or tiles, icons, and interactivity such as hover effects and clickable links to navigate users to the respective category pages.

Ensure Responsiveness and Accessibility: The component will be fully responsive, ensuring it works seamlessly across various screen sizes and devices. I will also ensure it follows accessibility best practices to provide an inclusive experience for all users.\

Test and Optimize: After implementing the component, I will test it for functionality and performance to ensure smooth user interactions and fast loading times.
Estimated Time: 8 hours.

I am excited to contribute to this project and collaborate with your team. Thank you for considering my application!

Best regards,
Super Franky

**Comment by Prosper1218** [comment]
hello, I'm Prosper williams. A frontEnd/Blockchain Developer (Nextjs/React/Cairo). I'd really love to jump on this task. ETA is within 6hrs.
 I'm a first time contributor.
Thank you.

**Comment by Ugo-X** [comment]
@FrankiePower assigned

**Comment by Ugo-X** [comment]
@FrankiePower what is the update?

**Comment by sonkeydotcom** [comment]
Let me handle this issue!
