### ISSUE TITLE
Build the Events page for logged in users

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#21]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. events-loggedIn.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located events-loggedIn folder, also within the app, so that I can access it when navigating to the /  events-loggedIn

Note!! the "side nav for logged in users and the explore categories component" have already been built, all you have to do is import it. Do not go building another one.

**Comment by yusuftomilola** [comment]
I would love to work on this issue and would deliver within the timeframe, giving you feedbacks and updates as the task progresses.

**Comment by KuchiMercy** [comment]
Could I try solving this?

**Comment by Levi-Ojukwu** [comment]
Hello, @Ugo-X, I would like to work on this issue.

##About Me
I am a Web3 full-stack developer and alumni of Web3Bridge, with expertise in blockchain technology and frontend engineering. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries.

## How To Tackle This Issue
-  To tackle this issue, I will first study the UI design properly to understand the design's number variables and the page flow, for better page dimensions and layouts.
- I will create a component file named `EventLoggedInUser`.
- I will then import the `EventLoggedInUser` components inside the `app/events-loggedIn/page.tsx` file.
- I will ensure a responsive page implementation, making sure it works across all devices.

If assigned this issue, I will ensure compliance with the project's guidelines.

## ETA
8 - 10 Hours Max

**Comment by Emmanex01** [comment]
May I try my hand at this?

**Comment by austineblaise** [comment]
I am excited to apply for this issue. With my expertise in JavaScript ( Next.js, React, and TypeScript) and familiarity with frameworks like Vue, I can efficiently build components that align with the project requirements.


Here’s my plan:

Follow the Figma design.
Create and name the component file correctly, then import it into page.tsx.
Reuse the existing "side nav" and "explore categories" components.
Complete the task within the 10-hour ETA.


I’m looking forward to the opportunity to contribute and will do my best to deliver quality work.

**Comment by Nityam573** [comment]
Can I work on this, please?

**Comment by wheval** [comment]
Hello @Ugo-X,
I'm an experienced Frontend Developer and I can build this in the specified time!
Please assign.

**Comment by Amarjeet325** [comment]
Can I start working on this?

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, specializing in frontend technologies such as React, NextJS, and Javascript/Typescript. I am a recent graduate of Web3bridge Africa, the foremost blockchain developer community, and have contributed to several open-source projects. I am excited to bring my skills to this project.

For building the Events Page for logged-in users, my approach will be:

Review the Project Requirements and Design: I will start by reviewing the project structure, understanding the design and features required for the events page, and any API integrations needed for logged-in users.

Develop the Events Page: I will focus on creating a dynamic and personalized events page that displays events specific to logged-in users. Features will include event filtering, the ability to view detailed event information, RSVP options, and possibly options for event management if required.

Implement User Authentication and Personalization: I will ensure that the page interacts correctly with the authentication system to personalize the experience for logged-in users, showing events based on their preferences, past interactions, or subscription status.

Ensure Responsiveness and User Experience: The page will be fully responsive, ensuring a seamless experience across different devices, and will be designed to provide a smooth user journey for interacting with the events.

Test and Optimize: After implementation, I will test the functionality to ensure everything is working as expected and optimize for performance.
Estimated Time: 12 hours.

I look forward to contributing to this project and collaborating with your team. Thank you for considering my application!

Best regards,
Super Franky

**Comment by deeseeker** [comment]
Can I take this issue? I have studied the design and I will do the following:

Create events-loggedIn file for logged in users
import the component for use in the page.tsx file located in the events-loggedin folder and within the app
I will carefully convert and. consider the responsiveness of the design and stick to the ETA

**Comment by sonkeydotcom** [comment]
I'd like to handle this task.
