### ISSUE TITLE
Build Event page for guest users

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#22]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. events-guest.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the events-guest folder, also within the app, so that I can access it when navigating to the / events-guest .

Note!! the "side nav for logged in users(you can import this and edit it for the guest users) and the explore categories component" have already been built, all you have to do is import it. Do not go building another one.

**Comment by portableDD** [comment]
May I take this issue on?
Mind if I take this issue?
My name is Dorcas, a software developer with React and Typescript, my eta is 8 hours, and I have seen the design I will be using tailwind css for styling, and i understand the guideline for this.

Thanks

**Comment by KuchiMercy** [comment]
May I be assigned to this?

**Comment by Emmanex01** [comment]
I'd love to work on this, to improve on my skills! 
Hope you don't mind assigning to me?

**Comment by A6dulmalik** [comment]
May I handle this issue? I've viewed the figma design and I would deliver at the expected ETA.

**Comment by austineblaise** [comment]
I’d like to take on this issue. I’m a frontend/ JavaScript/Blockchain developer with experience building interfaces from scratch and using frameworks. This is my second time participating in Only Dust, and I’m excited to contribute again.

I’ll follow the Figma design closely, appropriately name the file (e.g., events-guest.tsx), and import the component into page.tsx. I’ll also reuse the pre-built side nav and explore categories components as instructed.

I’m committed to delivering the task within the 10-hour ETA.

Looking forward to your approval.

**Comment by austineblaise** [comment]
I am excited to apply for this issue. With my expertise in JavaScript ( Next.js, React, and TypeScript) and familiarity with frameworks like Vue, I can efficiently build components that align with the project requirements.


Here’s my plan:

Follow the Figma design.
Create and name the component file correctly, then import it into page.tsx.
Reuse the existing "side nav" and "explore categories" components.
Complete the task within the 10-hour ETA.


I’m looking forward to the opportunity to contribute and will do my best to deliver quality work.

**Comment by Nityam573** [comment]
Could I try solving this?

**Comment by OWK50GA** [comment]
Hi, @Ugo-X I can handle this

**Comment by wheval** [comment]
Hello @Ugo-X,
I'm an experienced Frontend Developer and I can build this in the specified time!
Please assign.

**Comment by Amarjeet325** [comment]
May I handle this issue?

**Comment by phertyameen** [comment]
Can I be assigned this task? I can deliver within the ETA

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, specializing in frontend technologies such as React, NextJS, and Javascript/Typescript. I am a recent graduate of Web3bridge Africa, the foremost blockchain developer community. I have contributed to several open-source projects and am excited about the opportunity to contribute to this one.

For building the Event Page for guest users, my approach will be:

Review the Project Structure and Requirements: I will begin by reviewing the project structure, understanding the provided wireframes or Figma designs, and gathering all necessary resources to ensure the event page is aligned with the overall design and functionality.
Develop the Event Page: I will focus on creating a seamless user experience for guest users. This will include displaying event details, ensuring proper layout, and implementing features like RSVP functionality, event date/time, location, and other relevant event information.
Ensure Responsiveness and Accessibility: The page will be fully responsive, ensuring it works across various devices, and it will follow best practices for accessibility to ensure an inclusive experience for all users.
Test and Optimize: Once the page is developed, I will thoroughly test the functionality and performance, ensuring that everything works smoothly and the page loads efficiently.
Estimated Time: 12 hours.

I am excited about the opportunity to contribute to this project and look forward to working with your team. Thank you for considering my application!

Best regards,
Super Franky

**Comment by 3th-Enjay** [comment]
Could I take a shot at this?

**Comment by sonkeydotcom** [comment]
Would love to tackle this!
