### ISSUE TITLE
Build the Home Page

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#25]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. home-page.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the home-page folder, also within the app, so that I can access it when navigating to the / home-page route .

#### Please endeavour to deliver task in above ETA. Failure to do so results in issue being reassigned

**Comment by ussyalfaks** [comment]
I'd like to work on replicating this design. I’ll create a file in the components folder and write the code there. After that, I’ll import the component into the  home-page folder so it can be accessed when navigating to /home-page route .

**Comment by deeseeker** [comment]
Hi,

I am a frontend developer proficient in react, nextjs, typescript and css. I have gone through the design and I will convert the figma file and handle the responsiveness within the ETA. Thanks

**Comment by OWK50GA** [comment]
Hi, @Ugo-X
I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.
I will deliver within the time provided if assigned

**Comment by phertyameen** [comment]
I'm a new contributor and I would love to work on this. I can deliver within the specified ETA

**Comment by Prosper1218** [comment]
hello, I'm Prosper williams. A frontEnd/Blockchain Developer (Nextjs/React/Cairo). I have gone through the design and it's something i'd really love to jump on. ETA is within 12hrs.
So can I handle this one ?? I'm a first time contributor.
Thank you.

**Comment by 3th-Enjay** [comment]
I'd like to take this issue.
