### ISSUE TITLE
Build the create event component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#27]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. create-event.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the create-event folder, also within the app, so that I can access it when navigating to the / create-event route .

#### Please endeavour to deliver task in above ETA. Failure to do so results in issue being reassigned

**Comment by 3th-Enjay** [comment]
May I handle this issue?

**Comment by Prosper1218** [comment]
i've gone through the design, and i'd like to work on this. 
ETA is within 6hrs.

**Comment by Prosper1218** [comment]
i've gone through the design, and i'd like to work on this.
ETA is within 6hrs.

**Comment by Ugo-X** [comment]
@Prosper1218 assigned

**Comment by Prosper1218** [comment]
i'll send a dm on telegram now.
