### ISSUE TITLE
Build the Rewards/NFT/event component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#3]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. reward-nft.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the reward-nft folder, also within the app, so that I can access it when navigating to the / reward-nft route.

#### Please endeavour to deliver task in above ETA. Failure to do so results in issue being reassigned

**Comment by Benjtalkshow** [comment]
Can i be assigned to this?

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through the Design, Study, and be in sync with the flow of the Design
- I will then start the Rewards/NFT/event component UI implementation inside the `app/reward-nft/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, e.t.c
- I will make sure the UI implementation works across all devices

## ETA
12 hours as stated above

**Comment by BigBen-7** [comment]
I’d like to help with this.

**Comment by sublime247** [comment]
Kindly assign this task to me @Ugo-X , I would love to take this up

**Comment by Holamite** [comment]
## About me
I’m passionate about making Web3 technology more accessible. We all know that user experience is one of the biggest challenges and barriers to bringing new users into the decentralized world. That’s why I focus on creating intuitive and user-friendly applications powered by smart contracts.

## My Plan
If I’m assigned this task, I’ll start by reviewing the Figma design to ensure I fully understand the layout and styling. I’ll create the required component (e.g., reward-nft.tsx) in the components folder, import it into the page.tsx file, and make sure it works properly with the /reward-nft route. I’ll focus on building the component to match the design, testing it thoroughly, and delivering it within the 12-hour deadline. If I encounter any issues, I’ll communicate them quickly and suggest improvements if needed.

**Comment by portableDD** [comment]
Would love to tackle this!

**Comment by Benjtalkshow** [comment]
@Ugo-X 
Are we to use shadcn components?
