### ISSUE TITLE
Build the rewards page

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#4]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. rewards.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the rewards folder, also within the app, so that I can access it when navigating to the / rewards route.

please note!! that the ""side nav"" is already built, so all you have to do is import, no need to build a new one

#### Please endeavour to deliver task in above ETA. Failure to do so results in issue being reassigned

**Comment by 3th-Enjay** [comment]
Hello after going through the figma file , I have a clear understanding of what needs to be done and how to go about it with my experience in Frontend

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through the Design, Study, and be in sync with the flow of the Design
- I will then start the Rewards page UI implementation inside the `app/rewards/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, e.t.c
- I will make sure the UI implementation works across all devices

## ETA
24 hours as stated above

**Comment by emarc99** [comment]
Is it okay if I tackle this?

**Comment by BigBen-7** [comment]
Could I take a shot at this?

**Comment by sublime247** [comment]
I would love to take this up
I have vast experience in building of frontend application, building this wouldn't take longer time as I have check out the design
Thanks

**Comment by Holamite** [comment]
## About me
I’m passionate about making Web3 technology more accessible. We all know that user experience is one of the biggest challenges and barriers to bringing new users into the decentralized world. That’s why I focus on creating intuitive and user-friendly applications powered by smart contracts.

## My Plan
 I’m assigned this task, I’ll start by reviewing the Figma design to ensure the component aligns with the provided visuals. I’ll create the rewards.tsx file in the components folder, structure it according to the design, and import it into the page.tsx file in the rewards folder to ensure it works with the /rewards route. I’ll thoroughly test the component to verify functionality and responsiveness before delivering it within the 24-hour ETA. If I encounter any challenges or have suggestions for improvement, I’ll communicate promptly.

**Comment by phertyameen** [comment]
I am new contributor and I can handle this issue. kindly assign it to me.

**Comment by portableDD** [comment]
Can I work on this, please?
Hi, I am Emmanuel Dorcas, a software developer with React js and Typescript.
my estimated timeframe is 20 hours:

how I will tackle this:
1. first create a file.
2.Then, import that Component into the page.tsx
3. then I make sure the routing and navigation works properly.

**Comment by A6dulmalik** [comment]
Hello, I am Abdulmalik and I'm interested in taking this task, I've reviewed the figma and woukd create the reward page in the components folder utilising the necessary and available components in the folder at the expected ETA.
Thank you.

**Comment by yusuftomilola** [comment]
Is this issue still available? Can I take this from here?

**Comment by Ugo-X** [comment]
assigned @BigBen-7 please join the telegram group:  https://t.me/explorebeyondzerocheck

**Comment by Ugo-X** [comment]
Gm ser, 18 hours ETA has been reached, what is the udpate?

**Comment by BigBen-7** [comment]
> Gm ser, 18 hours ETA has been reached, what is the udpate?

@iamUgo_X  Good morning i was given the rewards page to push and i just saw your comment now on github, please i apologize, i am already done i am making my final touches then i create a PR, reason for my delay was that all my devices went off at the moment of rounding up.... so roughly 30mins i should have created a pr

**Comment by Ugo-X** [comment]
PR still not up?
