### ISSUE TITLE
Build the Checkin modal component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#5]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. check-in.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the check-in folder, also within the app, so that I can access it when navigating to the /check-in route.

**Comment by Benjtalkshow** [comment]
@Ugo-X 
Can i get my hands on this?

**Comment by emarc99** [comment]
Mind if I take this issue?

**Comment by BigBen-7** [comment]
Mind if I take this issue?
 I can complete the expected ETA.

Looking forward to contributing!!

**Comment by 3th-Enjay** [comment]
Can I contribute to this one?

**Comment by Holamite** [comment]
## About me
I’m passionate about making Web3 technology more accessible. We all know that user experience is one of the bipage.tsxallenges and barriers to bringing new users into the decentralized world. That’s why I focus on creating intuitive and user-friendly applications powered by smart contracts.

## My Plan

If assigned this task, I’ll begin by reviewing the Figma design to ensure the check-in.tsx component aligns with the requirements. I’ll create the file in the components folder, implement the design and functionality, and import it into the page.tsx file within the check-in folder. This will make the component accessible at the /check-in route. I’ll thoroughly test for responsiveness and functionality, delivering the task within the 12-hour ETA. If any challenges arise, I’ll communicate immediately to avoid delays.

**Comment by phertyameen** [comment]
I can handle this issue. I will like to be assigned
