### ISSUE TITLE
Build the nft certification component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#6]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. nft-certification.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the nft-certification folder, also within the app, so that I can access it when navigating to the / nft-certification route.

**Comment by Prosper1218** [comment]
let me build this for you!
you can count on me to ensure my design responds to all screen sizes. 
I'll make my PR within 24hrs

**Comment by Benjtalkshow** [comment]
@Ugo-X 
Let me work on this

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through Design, Study, and be in sync with the flow of the Design
- I will then start the NFT Certification Component UI implementation inside the `app/nft-certification/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, e.t.c
- I will make sure the UI implementation works across all devices

## ETA
12 hours as stated above

**Comment by 3th-Enjay** [comment]
Hello after going through the figma file , I have a clear understanding of what needs to be done and how to go about it with my experience in Frontend

**Comment by DotworldX** [comment]
Could I be assigned to this?

**Comment by A6dulmalik** [comment]
Hi, I'm Abdulmalik.
I would like to be assigned this task to deliver based on the figma design at the expected ETA.

**Comment by BigBen-7** [comment]
I’d love to work on this! I’ll use reusable components and Tailwind CSS to build the page efficiently while keeping the design clean and responsive. I can complete the expected ETA.

**Comment by Levi-Ojukwu** [comment]
Hello @Ugo-X, Can I take care of this issue?

## About Me 
I am a web3 full stack developer and an alumni of Web3Bridge, with blockchain technology and frontend engineering expertise. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How To Resolve Issue
- To tackle this issue, I will first of all study the UI design properly to understand the number variables and the page flow, for a better page dimensions and layouts.
- Then inside the component folder, I will create a file named `NftCertification.tsx`
- I will then import the `NftCertification.tsx` component into  the `app/nft-certification/page.tsx` file and beging the page implementation.
- I will ensure a responsive page implementation, making sure it works across all devices.

If assigned this issue, I will ensure compliance with the project's guidelines.

## ETA
10 - 12 Hours max

**Comment by Ugo-X** [comment]
assigned goodluck
