### ISSUE TITLE
Build the dashboard page

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#7]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. dashboard.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the dashboard folder, also within the app, so that I can access it when navigating to the / dashboard route.

please note!! that the dashboard ""side nav and event card component"" are already built, so all you have to do is import, no need to build new ones

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
- First of all, I'll go through Design, Study, and be in sync with the flow of the Design
- I will then start the Dashboard Page UI implementation inside the `app/dashboard/page.tsx` file
- I will make sure to follow and implement every detail in the design
- I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, e.t.c
- I will make sure the UI implementation works across all devices

## ETA
24 hours as stated above

**Comment by 3th-Enjay** [comment]
Hello after going through the figma file , I have a clear understanding of what needs to be done and how to go about it with my experience in Frontend

**Comment by Ugo-X** [comment]
> ## About Me
> I’m a blockchain and frontend developer and a Web3bridge Alumni from CohortX, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.
> 
> ## Solution Plan
> * First of all, I'll go through Design, Study, and be in sync with the flow of the Design
> * I will then start the Dashboard Page UI implementation inside the `app/dashboard/page.tsx` file
> * I will make sure to follow and implement every detail in the design
> * I will follow and maintain the codebase structure using Typescript, Nextjs, TailwindCSS, e.t.c
> * I will make sure the UI implementation works across all devices
> 
> ## ETA
> 24 hours as stated above

please send me a dm on telegram

**Comment by DotworldX** [comment]
Could I take on this issue?

**Comment by BigBen-7** [comment]
I’d love to work on this! I’ll use reusable components and Tailwind CSS to build the page efficiently while keeping the design clean and responsive. I can complete the expected ETA.

Looking forward to contributing!

**Comment by JamesVictor-O** [comment]
Gm boss, I'm a frontend developer proficient with javascript, Typescript,React.js, Next.js and Tailwind css, also good in building visually appiling and responsive websites and will deliver within the given ETA.

**Comment by Levi-Ojukwu** [comment]
Hello @Ugo-X  May I take care of this?

## About Me 
I am a web3 full stack developer with blockchain technology and frontend engineering expertise. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in Solidity and Cairo has enabled me to design, develop, and deploy smart contracts on Ethereum and Starknet-based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How To Resolve Issue
- To tackle this issue, I will first of all study the UI design properly to understand the number variables and the page flow, for a better page dimensions and layouts.
- Then inside the component folder, I will create a file named `Dashboard.tsx`
- I will then import the `Dashboard.tsx` component into  the `app/dashboard/page.tsx` file and beging the page implementation.
- I will ensure a responsive page implementation, making sure it works across all devices.

If assigned this issue, I will ensure compliance with the project's guidelines.

## ETA
12 Hours

**Comment by Superfly101** [comment]
I would love to work on this. ETA -24 hours

Next.js app router and tailwindcss are my day to date stack

**Comment by yusuftomilola** [comment]
Dashboards are my specialty. Can I attempt this issue?

**Comment by Ugo-X** [comment]
@Superfly101 assigned please join the telegram group: https://t.me/explorebeyondzerocheck

ETA is 18 hours.

**Comment by Superfly101** [comment]
@Ugo-X I just joined the telegram group as JOYBOY, getting to work now
