### ISSUE TITLE
Build the event card component

### ISSUE THREAD

**Issue by Ugo-X** [Explore-Beyond-Innovations/ZeroCheck_Frontend#9]
Here is the link to the Figma
https://www.figma.com/design/Zz6iuJ14pMYzQtVsWB3l57/ZeroCheck-Components?node-id=0-1&p=f&t=jeTO0Wc16UunVOus-0

Create a file titled with the name of the component you are building (e.g. event-card.tsx) inside the components folder in the app. Then, import that Component into the page.tsx file located in the event-card folder, also within the app, so that I can access it when navigating to the / event-card route.

**Comment by sublime247** [comment]
Kindly assign this to me to get it done as soon as possible
Thanks

**Comment by Ibinola** [comment]
can i work on this?

**Comment by Ugo-X** [comment]
assigned,please check tg group
